# fly.toml app configuration file generated for full-stack-open-pokedex-frosty-hill-5173 on 2025-12-06T07:01:55-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'full-stack-open-pokedex-frosty-hill-5173'
primary_region = 'lhr'

[env]
  PORT = "3000" # add this where PORT matches the internal_port below

[processes]
  app = "node app.js" # add this

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.http_checks]]
  interval = "15s"        # how often to run the check
  timeout = "2s"          # how long to wait for a response
  method = "get"          # HTTP method
  path = "/version"       # endpoint to check
  protocol = "http"       # or "https" if your app enforces it
  grace_period = "10s"    # time to wait after starting before first check

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[deploy]
  strategy = "canary"