
name: Fly Deploy
on:
  push:
    branches:
      - master    # change to main if needed
        
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Deploy to Fly.io
        id: deploy_step
        if: ${{ github.event_name == 'push' }}
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Verify deployment health
        run: curl -f https://full-stack-open-pokedex-frosty-hill-5173.fly.dev/health

      - name: Notify success
        if: ${{ steps.deploy_step.outcome == 'success' }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        uses: rjstone/discord-webhook-notify@v2
        with:
          color: #008000
          title: |
            A new version of Pokedex was deployed
            Commit: https://github.com/${{ github.repository }}/commit/${{ github.sha }}

      - name: Notify failure
        if: ${{ failure() }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        uses: rjstone/discord-webhook-notify@v2
        with:
          color: #FF0000
          details: |
            Build fail
            Commit: https://github.com/${{ github.repository }}/commit/${{ github.sha }}

  tag_release:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch